### ISSUE TITLE
How To Mock Or Config EFSecondLevelCache.Core In Unit Testing?

### ISSUE THREAD

**Issue by MohsenKasraeifar** [VahidN/EFSecondLevelCache.Core#35] opened 2019-04-28 10:40 UTC
# Summary of the issue
When we use ``` EFSecondLevelCache.Core for  ``` for caching query, and write a test for these methods, get an exception in saveChange.
## Exception:
```
Unable to resolve service for type 'EFSecondLevelCache.Core.Contracts.IEFCacheServiceProvider'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.

```
Is there a way for mocked or inject config  EFSecondLevelCache.Core in unit testing?

**Comment by VahidN** [comment] 2019-04-28 13:53
It's duplicate of #https://github.com/VahidN/EFSecondLevelCache.Core/issues/31

**Closed by VahidN** 2019-04-28 13:53 UTC
