### ISSUE TITLE
Unable to cast object of type 'EFSecondLevelCache.Core.Contracts.EFCacheKey' to type **

### ISSUE THREAD

**Issue by fishen** [VahidN/EFSecondLevelCache.Core#5] opened 2017-04-15 11:29 UTC
I used redis for cahce provider in my app, when the first time to fetch data from db, it will return a empty result and cache the result to the redis, but i found the cached data is incorrent, the cached value is '**{"CacheDependencies": []}**' and the value type is '**EFSecondLevelCache.Core.Contracts.EFCacheKey, EFSecondLevelCache.Core, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null**' , so it willl throw a castexception when attemp read again.

**Code:**
`var entity=context.Set<ProductCategorie>().Where(m=>!m.Deleted).Cacheable().FirstOrDefault();`

**Error:**
`System.InvalidCastException:“Unable to cast object of type 
'EFSecondLevelCache.Core.Contracts.EFCacheKey' to type 'Jazea.Chain.Domain.Entity.ProductCategorie'.”`

**Comment by fishen** [comment] 2017-04-15 12:24
It works when use ToList() or Count().

```
public static void AddCache(IServiceCollection services)
{
    var provider = services.BuildServiceProvider();
    var config = provider.GetService<IConfigurationRoot>();
    var redisConnStr = config.GetValue<string>("RedisConnetionString");
    services.AddEFSecondLevelCache();
    services.AddSingleton(typeof(ICacheManager<>), typeof(BaseCacheManager<>));
    var jss = new JsonSerializerSettings()
    {
        NullValueHandling = NullValueHandling.Ignore,
        ReferenceLoopHandling = ReferenceLoopHandling.Ignore
    };
    services.AddSingleton<ICacheManagerConfiguration>(
        new CacheManager.Core.ConfigurationBuilder()
            .WithJsonSerializer(jss, jss)
            .WithRedisConfiguration("Redis", redisConnStr)
            .WithRedisCacheHandle("Redis")
            .WithExpiration(ExpirationMode.None, TimeSpan.FromHours(1))
            .Build()
    );
}
```
```
public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
{
    loggerFactory.AddConsole(Configuration.GetSection("Logging"));
    loggerFactory.AddDebug();
    app.UseEFSecondLevelCache();
    app.Map("/api", c => c.UseMvc());
}

```

**Comment by fishen** [comment] 2017-04-15 12:33
![1](https://cloud.githubusercontent.com/assets/17705466/25063584/bfc42036-221a-11e7-9043-c29c2bfddf0d.JPG)
![default](https://cloud.githubusercontent.com/assets/17705466/25063586/c6bb1da4-221a-11e7-9acb-c83014a7098a.JPG)

**Comment by fishen** [comment] 2017-04-15 12:48
Because i  set `NullValueHandling = NullValueHandling.Ignore`, so the cached value is incomplete. 
The complate info is :
```
{
  "Key": null,
  "KeyHash": null,
  "CacheDependencies": []
}
```
It will throw InvalidCastException while reading the cahed value .

**Comment by VahidN** [comment] 2017-04-15 16:03
- Please update your NuGet packages (all of them). You are not using the latest versions.
- I can't reproduce your issue. [I added Redis related settings and services](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample/Startup.cs#L81). I can run both unit tests and also the sample web app with [the same FirstOrDefault method](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample/Controllers/HomeController.cs#L23):

![redis01](https://cloud.githubusercontent.com/assets/766010/25064928/c439a384-221a-11e7-8b9d-4317701243ca.png)

![redis02](https://cloud.githubusercontent.com/assets/766010/25064933/cca72faa-221a-11e7-85cd-19dae0a73cfc.png)


- The whole purpose of using the [CacheManager](https://github.com/MichaCo/CacheManager) as the infrastructure is to do not fighting with all of the available cache providers. `EFSecondLevelCache.Core` doesn't know anything about Redis or .... It just uses the public API of the CacheManager to insert/update/get info.

**Comment by VahidN** [comment] 2017-04-16 06:00
It's fixed via https://github.com/VahidN/EFSecondLevelCache.Core/commit/15839e39b10ef581139fe558a64d0adf85a8c074 (Improved null object detection).
```
PM> update-package
```

**Closed** 2017-04-16 13:06 UTC
